package ErrigalMotor;

import javax.swing.JOptionPane;

/**
 *
 * @author Team 3
 * @since 15/04/2019
 * @version 1.0
 */
public class frStock extends javax.swing.JFrame {

    /**
     * Class variables
     */
    private DatabaseConnection carConnection;
    private Stock[] carArray;
    private int currentIndex;
    private int numberOfRecords;

    /**
     * Creates new form frStock
     */
    public frStock() {
        initComponents();
        setLocationRelativeTo(null);
        carConnection = new DatabaseConnection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblRegistration = new javax.swing.JLabel();
        lblMake = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblFuel = new javax.swing.JLabel();
        lblEngineSize = new javax.swing.JLabel();
        lblFuelConsumption = new javax.swing.JLabel();
        txtRegistration = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtFuelType = new javax.swing.JTextField();
        txtEngineSize = new javax.swing.JTextField();
        txtFuelConsump = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        lblMileage = new javax.swing.JLabel();
        txtMileage = new javax.swing.JTextField();
        lblOf = new javax.swing.JLabel();
        txtMaxIndex = new javax.swing.JTextField();
        txtCurrentIndex = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnAddCar = new javax.swing.JButton();
        btnSelectForAppt = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRegistration.setText("Registration");

        lblMake.setText("Brand");

        lblModel.setText("Model");

        lblPrice.setText("Price");

        lblFuel.setText("Fuel Type");

        lblEngineSize.setText("Engine Size");

        lblFuelConsumption.setText("Fuel Consumption");

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        lblMileage.setText("Mileage");

        lblOf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOf.setText("of");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnPrevious)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)
                        .addGap(0, 77, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMake, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEngineSize, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFuelConsumption, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMileage)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(txtCurrentIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMileage)
                            .addComponent(txtFuelConsump)
                            .addComponent(txtEngineSize)
                            .addComponent(txtFuelType)
                            .addComponent(txtPrice)
                            .addComponent(txtModel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOf)
                                .addGap(32, 32, 32)
                                .addComponent(txtMaxIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRegistration)
                            .addComponent(txtBrand))))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOf)
                    .addComponent(txtMaxIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrentIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMake, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEngineSize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEngineSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuelConsumption, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFuelConsump, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMileage)
                    .addComponent(txtMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)))
        );

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitle.setText("Car Stock");

        btnAddCar.setText("Add New Car");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        btnSelectForAppt.setText("Select Car For Appointment");
        btnSelectForAppt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectForApptActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnLoad.setText("View Cars");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelectForAppt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddCar)))
                .addGap(134, 134, 134))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddCar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelectForAppt)
                        .addGap(288, 288, 288)
                        .addComponent(btnHome)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        numberOfRecords = carConnection.numRecordsInQuery;
        //button will move to the record after current one         
        //if the last record is showing there will be no response         
        if (currentIndex < numberOfRecords - 1) {
            currentIndex++;
            txtCurrentIndex.setText(Integer.toString(currentIndex + 1));
            txtRegistration.setText(carArray[currentIndex].getRegistration());

            txtBrand.setText(carArray[currentIndex].getBrand());
            txtModel.setText(carArray[currentIndex].getModel());
            txtPrice.setText(Double.toString(carArray[currentIndex].getPrice()));
            txtFuelType.setText(carArray[currentIndex].getFuelType());
            txtEngineSize.setText(Double.toString(carArray[currentIndex].getEngineSize()));
            txtFuelConsump.setText(Double.toString(carArray[currentIndex].getFuelConsumption()));
            txtMileage.setText(Integer.toString(carArray[currentIndex].getMileage()));
        }


    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        //button will move to the record before current one  
        //if the first record is displayed then there will be no response    
        if (currentIndex != 0) {
            currentIndex--;
            txtCurrentIndex.setText(Integer.toString(currentIndex + 1));
            //display the car details at currentIndex 
            txtRegistration.setText(carArray[currentIndex].getRegistration());

            txtBrand.setText(carArray[currentIndex].getBrand());
            txtModel.setText(carArray[currentIndex].getModel());
            txtPrice.setText(Double.toString(carArray[currentIndex].getPrice()));
            txtFuelType.setText(carArray[currentIndex].getFuelType());
            txtEngineSize.setText(Double.toString(carArray[currentIndex].getEngineSize()));
            txtFuelConsump.setText(Double.toString(carArray[currentIndex].getFuelConsumption()));
            txtMileage.setText(Integer.toString(carArray[currentIndex].getMileage()));

        }

    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        /**
         * This button will check that the user is signed in with the
         * appropriate login credentials and if so will allow them to add a new
         * car
         */
        if (frSignIn.user1 != null) {
            if (frSignIn.user1.getAccLevel() == 2) {

                boolean done = carConnection.addNewCar(txtRegistration.getText(), txtBrand.getText(), txtModel.getText(), Double.valueOf(txtPrice.getText()), txtFuelType.getText(), Double.valueOf(txtEngineSize.getText()), Double.valueOf(txtFuelConsump.getText()), Integer.valueOf(txtMileage.getText()));
                if (done) {
                    JOptionPane.showMessageDialog(this, "Car added", "Adding Record", JOptionPane.PLAIN_MESSAGE);
                    //reload the records by calling the btnLoadActionPerformed method with the 
                    //event  
                    btnLoadActionPerformed(evt);

                } else {
                    JOptionPane.showMessageDialog(this, "Car not added", "Error", JOptionPane.PLAIN_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Admin priviliges required");
            }
        } else {
            JOptionPane.showMessageDialog(null, "User not logged in");
        }

    }//GEN-LAST:event_btnAddCarActionPerformed

    private void btnSelectForApptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectForApptActionPerformed
        /**
         * The following button will check to see if the user if logged in and
         * if so will load the frAppointment form so that the user can confirm
         * their appointment with the selected car
         *
         * @param evt
         */
        if (frSignIn.user1 != null) {
            String carSelected = txtRegistration.getText();

            this.setVisible(false);
            new frAppointment(carSelected).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "User must be logged in");

        }

    }//GEN-LAST:event_btnSelectForApptActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.setVisible(false);
        AppData.frHomeScreen.setVisible(true);

    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        /**
         * The button btnLoad will load the details of the cars from the
         * database and display them on screen
         *
         * @param evt
         */
        try {
            //set up array to store the data sent back from the DatabaseConnection           
            carArray = carConnection.getAllCars();
            //number of items in the array 
            numberOfRecords = carConnection.numRecordsInQuery;
            currentIndex = 0;
            if (numberOfRecords != 0) {
                //display the first car details 

                txtRegistration.setText(carArray[currentIndex].getRegistration());

                txtBrand.setText(carArray[currentIndex].getBrand());
                txtModel.setText(carArray[currentIndex].getModel());
                txtPrice.setText(Double.toString(carArray[currentIndex].getPrice()));
                txtFuelType.setText(carArray[currentIndex].getFuelType());
                txtEngineSize.setText(Double.toString(carArray[currentIndex].getEngineSize()));
                txtFuelConsump.setText(Double.toString(carArray[currentIndex].getFuelConsumption()));
                txtMileage.setText(Integer.toString(carArray[currentIndex].getMileage()));

                //display the current index for current and last record                 
                txtCurrentIndex.setText(Integer.toString(currentIndex + 1));
                txtMaxIndex.setText(Integer.toString(numberOfRecords));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSelectForAppt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEngineSize;
    private javax.swing.JLabel lblFuel;
    private javax.swing.JLabel lblFuelConsumption;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblMileage;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOf;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCurrentIndex;
    private javax.swing.JTextField txtEngineSize;
    private javax.swing.JTextField txtFuelConsump;
    private javax.swing.JTextField txtFuelType;
    private javax.swing.JTextField txtMaxIndex;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRegistration;
    // End of variables declaration//GEN-END:variables
}
